# Copyright 2021 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Pull docker cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
   docker pull gcr.io/$PROJECT_ID/dbt-builder:latest || exit 0
- name: gcr.io/cloud-builders/docker
  id: Build Airflow DAGs Builder
  args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/dbt-builder',
      '--cache-from', 'gcr.io/$PROJECT_ID/dbt-builder:latest',
      './'
    ]

- name: gcr.io/cloud-builders/docker
  id: Push Airflow DAGs Builder
  args: [
      'push',
      'gcr.io/$PROJECT_ID/dbt-builder:latest'
    ]

- name: gcr.io/cloud-builders/gsutil
  id: Get SA key
  args:
  - cp
  - gs://pso-dbt-airflow-demo-bucket/key/pso-dbt-airflow-demo-a87a347b6390.json
  - key/pso-dbt-airflow-demo-a87a347b6390.json

- name: 'gcr.io/$PROJECT_ID/airflow-dags-builder'
  id: Generate documentation
  entrypoint: bash
  args:
  - -c
  - |
    dbt docs generate --vars '{"project_id": "pso-dbt-airflow-demo","bigquery_location": "us","key_file_dir": "key/pso-dbt-airflow-demo-a87a347b6390.json", "execution_date":"1970-01-01"}' --profiles-dir .dbt --target tests

    
- name: gcr.io/cloud-builders/gsutil
  id: Copy the target to GCS
  args:
  - -m
  - rsync
  - -r
  - -c
  - -x
  - .dockerignore|key|logs|models|tests|.dockerignore|.gitignore|cloudbuild.yaml|Dockerfile|README.md|.git
  - .
  - gs://us-central1-cloud-composer--646f5756-bucket/data/dbt-docs