steps:
- name: 'gcr.io/ccm-dev-sandbox/terraform'
  dir: 'infra-as-code/environment-deploy'
  args: ['init']

- name: 'gcr.io/ccm-dev-sandbox/terraform'
  dir: 'infra-as-code/environment-deploy'
  args: ['destroy','-var-file=input.tfvars','-auto-approve']