steps:
- id: lint
  name: gcr.io/$PROJECT_ID/make
  args: [test]
  waitFor: ['-']
- id: tools/hive-bigquery
  name: google/cloud-sdk
  args: [gcloud, builds, submit, tools/hive-bigquery/, --config=tools/hive-bigquery/cloudbuild.yaml]
  waitFor: ['-']
- id: examples/cloud-composer-examples
  name: google/cloud-sdk
  args: [gcloud, builds, submit, examples/cloud-composer-examples/,
    --config=examples/cloud-composer-examples/cloudbuild.yaml]
  waitFor: ['-']
- id: examples/dataflow-python-examples
  name: google/cloud-sdk
  args: [gcloud, builds, submit, examples/dataflow-python-examples, --config=examples/dataflow-python-examples/cloudbuild.yaml]
  waitFor: ['-']
