steps:
###########################################################
# Step 1: Create a Docker image with Python installed
###########################################################
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/dataflow-batch-python-examples'
    - '.'

###########################################################
# Step 2: Run unit tests
###########################################################
- name: 'gcr.io/$PROJECT_ID/dataflow-batch-python-examples'
  entrypoint: 'python3'
  args: ["-m",  "unittest"]
