view-generator:
  hive:
    thrift-uris: "thrift://10.119.0.57:9083"
    time-zone: "Asia/Kolkata"
    filters:
      table-type-deny-list: "VIRTUAL_VIEW"
      file-format-deny-list: "JSON"
      delta-processing: true

  bigquery:
    location: "asia-south1"
    project: "fks-batch-gcs-storage"
    external-table-dataset-prefix: "bqext_"
    view-dataset-prefix: "bq_"
    authorize-view-datasets: true
    require-partition-filter: false
    hive-bq-sync: true
    audit:
      dataset: "view_generator_audit"
      hive-metastore-stats-table: "hive_table_stats"
      tool-execution-stats-table: "bq_external_view_stats"
      select-view-check: true

