
steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
    dir: 'tools/bq-visualizer'

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run','ng','--prod', 'build']
    dir: 'tools/bq-visualizer'
