
steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
    dir: 'tools/bq-visualizer'

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    #args: [ 'run','ng', 'build', '--prod' ]
    args: ['run', 'build', '--prod']
    dir: 'tools/bq-visualizer'
  
artifacts:
  objects:
    location: 'gs://${_BQVISUALISER_BUCKET}/deployment_$BUILD_ID'
    paths: ['tools/bq-visualizer/dist/*']

  # store on GCS
  #- name: gcr.io/cloud-builders/gsutil
  #  args: ['-m', 'cp', '-r', '*', 'gs://${_BQVISUALISER_BUCKET}/deployment_$BUILD_ID']
  #  dir: '$REPO_NAME/dist'
  #  id: 'deploy'

