jobs:
- pysparkJob:
    properties:
      spark.pyspark.driver.python: '/usr/bin/python3'
    args:
    - /RC_2022-06.zst
    - cy-artifacts-services
    - "16384"
    mainPythonFileUri: gs://cy-artifacts-services/scripts/social_data_generator.py
  stepId: social-data-generator
placement:
  managedCluster:
    clusterName: cy-artifacts-dp-cluster-e
    config:
      gceClusterConfig:
        zoneUri: us-central1-a
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 500
        machineTypeUri: n1-standard-4
        imageUri: projects/cy-artifacts/global/images/reddit-data-cluster
      workerConfig:
        diskConfig:
          bootDiskSizeGb: 500
        machineTypeUri: n1-standard-4
        numInstances: 2
        imageUri: projects/cy-artifacts/global/images/reddit-data-cluster
      initializationActions:
        - executableFile: gs://cy-artifacts-services/scripts/initialize.sh
          executionTimeout: '3600s'
