kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: prod
  labels:
    environment: prod
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: prod-cluster-selector
spec:
  selector:
    matchLabels:
      environment: prod
