apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-app
  labels:
    name: tensorflow-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tensorflow-app
  template:
    metadata:
      labels:
        app: tensorflow-app
    spec:
      containers:
      - name: tensorflow-app
        image: gcr.io/${{GCP_PROJECT}}/tensorflow-app:latest
        env:
        - name: MODEL_NAME
          value: {model_name}
        ports:
        - containerPort: 8500
        - containerPort: 8501
        args: ["--model_config_file=/benchmark/models.config", {tensorflow_params}]

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: tensorflow-app
  name: tensorflow-app
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 8500
    targetPort: 8500
  - name: rest
    port: 8501
    targetPort: 8501
  selector:
    app: tensorflow-app
