kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-syncer
rules:
# read namespaces
- apiGroups: [""] 
  resources: ["namespaces"]
  verbs: ["get", "list"]
# create/update secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
