apiVersion: v1
kind: Service
metadata:
  name: prod-nodejs
  namespace: prod
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: nodejs
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-nodejs
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: gcr.io/titodo-anthos/hello-kubernetes@sha256:3249a3c875195a5d7f61564fc8cb2d3320c315f7a9eab337d7a68c9693ccdaa4
        name: nodejs
        ports:
        - containerPort: 8080
