runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  PROJECT_ID: <PROJECT_ID>
  CLOUD_STORAGE_BUCKET: <CLOUD_STORAGE_BUCKET>
  MODEL_NAME: <MODEL_NAME>
  MODEL_VERSION: <MODEL_VERSION>
