push-manifests:
  only:
    refs:
      - main
  stage: Push Manifests
  image: gcr.io/cloud-solutions-images/kustomize:3.7
  tags:
    - prod
  script:
  #- cp /working/.ssh/ssh-deploy /working/ssh-key
  - echo ${SSH_KEY} | base64 -d > /working/ssh-key
  - chmod 400 /working/ssh-key
  - export GIT_SSH_COMMAND="ssh -i /working/ssh-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  - git config --global user.email "${CI_PROJECT_NAME}-ci@${CI_SERVER_HOST}"
  - git config --global user.name "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  - git clone git@${CI_SERVER_HOST}:${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}-env.git -b stage
  - cd ${CI_PROJECT_NAME}-env
  - cp ../hydrated-manifests/stage.yaml stage.yaml
  - cp ../hydrated-manifests/production.yaml production.yaml
  - |
    # If files have changed, commit them back to the env repo in the staging branch
    if [ -z "$(git status --porcelain)" ]; then
      echo "No changes found in env repository."
    else
      git add stage.yaml stage.yaml
      git add production.yaml production.yaml
      git commit -m "${CI_COMMIT_REF_SLUG} -- ${CI_PIPELINE_URL}"
      git push origin stage
    fi