#@data/values
---
organization: '11111111'
bundles:
  pci-dss: false
  cis: false
compute:
  computeRestrictDiskSize:
    params:
      max_disksize: 100
  computeAllowedInstanceLabels:
    params:
      labels:
      - "label1"
      - "label2"

