#@data/values
---
organization: '11111111'
bundles:
  pci-dss: false
  cis: false
compute:
  computeAllowedInstanceMachineTypes:
    params:
      machine_types:
      - "n2"
      - "n2d"
  computeAllowedInstanceLabels:
    params:
      labels:
      - "label-0"
      - "label-1"
  computeAllowedDiskTypes:
    params:
      disk_types:
      - "pd-ssd"
      - "pd-standard"
  computeRestrictDiskSize:
    params:
      max_disksize: 100
  computeAllowedInstanceVpcs:
    params:
      networks:
      - "network-1"
      - "network-2"
dataproc:
  dataprocAllowedLabels:
    params:
      machine_types:
      - "n2"
      - "n2d"
  computeAllowedInstanceLabels:
    params:
      labels:
      - "label-0"
      - "label-1"
  computeAllowedDiskTypes:
    params:
      disk_types:
      - "pd-ssd"
      - "pd-standard"
  computeRestrictDiskSize:
    params:
      max_disksize: 100
  computeAllowedInstanceVpcs:
    params:
      networks:
      - "network-1"
      - "network-2"
storage:
  storageAllowedBucketLabels:
    params:
      labels:
      - "label-0"
      - "label-1"
  storageBucketEnforceNamingConvention:
    params:
      name_regex: "^(sin|cgk)"
gke:
  gkeAllowedAddons:
    params:
      addons:
      - "httpLoadBalancing"
      - "gcePersistentDiskCsiDriverConfig"
      - "horizontalPodAutoscaling"
  gkeAllowedGKEVersions:
    params:
      versions:
      - "1.29.4-gke.1043000"
      - "1.28.9-gke.1000000"
  gkeAllowedNodePoolImages:
    params:
      images:
      - "cos_containerd"
  gkeAllowedReleaseChannels:
    params:
      release_channels:
      - "REGULAR"