creditcards:
    project: 'cxt2-creditcards-dev'
    region: 'europe-west4' 
    docker_repo: 'europe-west4-docker.pkg.dev/cxt2-creditcards-dev/docker-repo'
    service_account: 'sa-mlops-dev@cxt2-creditcards-dev.iam.gserviceaccount.com'
    vertex_dataset_name: 'creditcards'
    raw_schema_dir: 'src/raw_schema'
    bucket: 'cxt2-creditcards-dev'
    limit: 5000
    version: 'v02'
    cloudfunction_region: 'europe-west4'
    artifactregistry_region: 'europe-west4'
    python_pkg_repo: 'pyrepo'
    bq:
       dataset: 'creditcards'
       location: 'EU'
       source_table: 'creditcards'
       ml_table: 'creditcards_ml'
    dataflow:
        subnet: 'default'
        service_account: 'sa-mlops-dev@cxt2-creditcards-dev.iam.gserviceaccount.com'
    featurestore_id: 'creditcards'
    git:
        repo_url: "git@github.com:javiergp/mlops-cc-t1"
        branch: "main"     
 
